name: CI

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    packages: write

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: checkout

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/noelxp/k8-flask-project/flask:$(date +%s)

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.ghcr_token }}

    - name: publish
      run: |
        docker push ghcr.io/noelxp/k8-flask-project/flask:$(date +%s)

